workflowVersion: 1.0.0
sources:
    accounting:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Accounting.yaml
    lending:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Lending.yaml
targets:
    accounting-ts:
        target: typescript
        source: accounting
        output: ./accounting
    lending-ts:
        target: typescript
        source: lending
        output: ./lending
